#!/usr/bin/env python3
# Python modules
from argparse import ArgumentParser
# alpacapy modules
from alpacapy.alpaca.obtain_runtime_information import obtain_runtime_information
from alpacapy.logger import Logger
from alpacapy.helper_functions import file_operations as fo


def setup_argument_parser():
    """ Creates the argument parser to pass commandline arguments.

    Returns
    -------
    ArgumentParser
        The fully created argument parser.
    """
    parser = ArgumentParser(prog="Obtain runtime information",
                            description="Obtain the runtime information from a log file generated by an alpaca run")
    # Add the basic other arguments
    parser.add_argument("log_file_path", help="The path to the log file from which runtime information should be taken", type=str)
    parser.add_argument("--quiet", action="store_false", dest="verbose", help="Disables verbosity logging", default=True)
    return parser


if __name__ == "__main__":
    """ Main part to be called when using the module with direct call. """
    parser = setup_argument_parser()
    options = parser.parse_args()

    options.log_file_path = fo.get_absolute_path(options.log_file_path)

    logger = Logger()

    logger.star_line_flush()
    logger.blank_line()

    obtain_runtime_information(options.log_file_path, options.verbose)

    logger.blank_line()
    logger.star_line_flush()
